const menu = [
  {
    id: 1,
    category: "Phone",
    about1: "Manufacturer",
    about2: "Type",
    about3: "Main camera",
    about4: "Front camera",
    about5: "Memory (Prompt / Internal)",
    about6: "Color",
    about7: "Year",
    about8: "NFC",
    about9: "Wifi",
    about10: "Fast Power Assembly",
    about11: "Network",
    about12: "Display",
    about13: "Video format",
    about14: "Bluetooth",
    about15: "Battery Type",
    about16: "Battery capacity",
    aboutproduct: [
      "Manufacturer",
      "Type",
      "Main Camera",
      "Front Camera",
      "Memory (Prompt / Internal)",
      "Color",
      "Year",
      "NFC",
      "Fast Power Assembly",
      "Network",
      "Display",
      "Video Format",
      "Bluetooth",
      "Battery Type",
      "Battery Capacity",
    ],
  },
  {
    id: 2,
    category: "Tablet",
    about1: "Manufacturer",
    about2: "Year",
    about3: "Operating System Version",
    about4: "Color",
    about5: "Wi-Fi",
    about6: "Screen",
    about7: "Memory (Prompt / Internal)",
    about8: "Main camera",
    about9: "Front camera",
    about10: "Video Shooting",
    about11: "4G",
    about12: "3G",
    about13: "Type of Energy",
    about14: "Battery",
    about15: "Processor",
    about16: "GPS",
    aboutproduct: [
      "Manufacturer",
      "Year",
      "Operating System Version",
      "Color",
      "Wi-Fi",
      "Screen",
      "Memory (Prompt / Internal)",
      "Main Camera",
      "Front Camera",
      "Video Shooting",
      "4G",
      "3G",
      "Type of Energy",
      "Battery",
      "Processor",
      "GPS",
    ],
  },
  {
    id: 3,
    category: "Notebook",
    about1: "Manufacturer",
    about2: "Model",
    about3: "Display Quality Indication",
    about4: "Memory",
    about5: "Wi-Fi",
    about6: "USB",
    about7: "Color",
    about8: "Category",
    about9: "Type of Video Card",
    about10: "Processor Code",
    about11: "Processor",
    about12: "SSD",
    about13: "HDD",
    about14: "Lan",
    about15: "HDMI",
    about16: "Situation",
    aboutproduct: [
      "Manufacturer",
      "Model",
      "Display quality indication",
      "Memory",
      "Wi-fi",
      "USB",
      "Color",
      "Category",
      "Type of video card",
      "Processor code",
      "Processor",
      "SSD",
      "HDD",
      "Lan",
      "HDMI",
      "Situation",
    ],
  },
];
export default menu;
